In [2]:
import numpy as np
import pandas as pd

dataset = pd.read_csv('C:\\Users\\AFFAN SHAIKH\\Desktop\\workspace\\GOT_Battle_Of_Blackwater_v2_FINAL\\train.csv')
print (dataset.head())


Y=dataset["bestSoldierPerc"]
dataset.drop(["soldierId","shipId","farthermostKill","attackId","bestSoldierPerc"],axis=1,inplace=True)


X=dataset


X.shape

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)


   soldierId     shipId  attackId  assists  greekFireItems  healthLost  \
0        0.0       24.0       0.0      0.0             5.0      247.30   
1        1.0   440875.0       1.0      1.0             0.0       37.65   
2        2.0   878242.0       2.0      0.0             1.0       93.73   
3        3.0  1319841.0       3.0      0.0             0.0       95.88   
4        4.0  1757883.0       4.0      0.0             1.0        0.00   

   knockedOutSoldiers  throatSlits  healingPotionsUsed  killRank  \
0                 2.0          0.0                 4.0      17.0   
1                 1.0          1.0                 0.0      45.0   
2                 1.0          0.0                 2.0      54.0   
3                 0.0          0.0                 0.0      86.0   
4                 0.0          0.0                 1.0      58.0   

        ...         numSaves  horseRideDistance  horseRideKills  \
0       ...              1.0              591.3             0.0   
1       ... 

In [3]:
from keras.optimizers import SGD
from keras.optimizers import Adam
from keras.optimizers import RMSprop
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.layers import Dropout
from keras import optimizers

model = Sequential()
model.add(Dense(20, input_dim=20, kernel_initializer='normal', activation='sigmoid'))
#model.add(Dropout(0.2))
model.add(Dense(20, kernel_initializer='normal', activation='sigmoid'))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model
model.compile(Adam(lr=0.01),loss='mean_squared_error',metrics=['mean_absolute_error'])
model.summary()
model.fit(X,Y,nb_epoch=3)

model1 = Sequential()
model1.add(Dense(20, input_dim=20, kernel_initializer='normal', activation='relu'))
#model.add(Dropout(0.2))
model1.add(Dense(6, kernel_initializer='normal', activation='sigmoid'))
model1.add(Dense(1, kernel_initializer='normal'))
# Compile model
model1.compile(Adam(lr=0.025),loss='mean_squared_error',metrics=['mean_absolute_error'])
model1.summary()
model1.fit(X,Y,nb_epoch=3)






Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 21        
Total params: 861
Trainable params: 861
Non-trainable params: 0
_________________________________________________________________


C:\Users\AFFAN SHAIKH\PycharmProjects\tre\venv\lib\site-packages\ipykernel_launcher.py:22: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/3
4357336/4357336 [==============================] - 191s 44us/step - loss: 0.0100 - mean_absolute_error: 0.0725
Epoch 2/3
4357336/4357336 [==============================] - 184s 42us/step - loss: 0.0094 - mean_absolute_error: 0.0702
Epoch 3/3
4357336/4357336 [==============================] - 184s 42us/step - loss: 0.0093 - mean_absolute_error: 0.0698
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 126       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 7         
Total params: 553
Trainable params: 553
Non-trainable params: 0
_________________________________________________________________


C:\Users\AFFAN SHAIKH\PycharmProjects\tre\venv\lib\site-packages\ipykernel_launcher.py:32: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/3
4357336/4357336 [==============================] - 187s 43us/step - loss: 0.0117 - mean_absolute_error: 0.0791
Epoch 2/3
4357336/4357336 [==============================] - 191s 44us/step - loss: 0.0118 - mean_absolute_error: 0.0792
Epoch 3/3
4357336/4357336 [==============================] - 193s 44us/step - loss: 0.0120 - mean_absolute_error: 0.0796


In [4]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X, Y)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [6]:
test = pd.read_csv('C:\\Users\\AFFAN SHAIKH\\Desktop\\workspace\\GOT_Battle_Of_Blackwater_v2_FINAL\\test.csv')

test.head()
#dataset.drop(["soldierId","shipId","farthermostKill"],axis=1,inplace=True)

test.drop(["Unnamed: 0","index","soldierId","attackId","shipId","farthermostKill"],axis=1,inplace=True)
test.head()

sc=StandardScaler()
test=sc.fit_transform(test)


In [10]:
predictions = model.predict(test)
predictions1=model1.predict(test)
y_pred=np.asarray(predictions[:,0])
y_pred = y_pred.clip(min=0)
y_pred1=np.asarray(predictions1[:,0])
y_pred1 = y_pred1.clip(min=0)



predictionsLR=regr.predict(test)


y_predLR=np.asarray(predictionsLR)
y_predLR = y_predLR.clip(min=0)


predictionsRF=rf.predict(test)


y_predRF=np.asarray(predictionsRF)
y_predRF = y_predRF.clip(min=0)




hybrid=[]
for i in range (len(y_pred)):
    hybrid.append((y_pred[i]+y_predRF[i]+y_predLR[i])/3)

In [11]:

def make_submission(prediction, sub_name):
  my_submission = pd.DataFrame({'soldierId':pd.read_csv('C:\\Users\\AFFAN SHAIKH\\Desktop\\workspace\\GOT_Battle_Of_Blackwater_v2_FINAL\\test.csv').soldierId,'bestSoldierPerc':prediction},columns=['soldierId','bestSoldierPerc'])
  my_submission.to_csv('{}.csv'.format(sub_name),index=False)
  print('A submission file has been made')



make_submission(y_pred,'C:\\Users\\AFFAN SHAIKH\\Desktop\\workspace\\submission_final')



A submission file has been made


In [12]:
np.corrcoef(y_predRF,y_pred1)

array([[1.        , 0.97371124],
       [0.97371124, 1.        ]])

In [13]:
np.corrcoef(y_predRF,y_predLR)

array([[1.        , 0.91468316],
       [0.91468316, 1.        ]])

In [14]:
np.corrcoef(y_predLR,y_pred1)

array([[1.        , 0.93802963],
       [0.93802963, 1.        ]])